### ISSUE TITLE
Bad performance / CPU limit on act-4 maps

### ISSUE THREAD

**Issue by WolfeStrider** [xoxor4d/p2-rtx#35]
Bug reported by wolfe_strider on Trello on November 5th

Description:
This happens in a bunch of act 4 maps

Example:
https://www.youtube.com/watch?v=T3jmYABFwAo
Preview image:
![Image](https://github.com/user-attachments/assets/14061a26-043a-4995-a244-d058a5faa1a9)

**Comment by xoxor4d** [comment]
This is happening due to other, larger map areas getting tagged as potentially visibility and thus, being rendered and is not related to the emncipation grill. The second layer of emancipation grill popping in and out of existance is already fixed.

**Comment by xoxor4d** [comment]
#95

**Comment by WolfeStrider** [comment]
> This is happening due to other, larger map areas getting tagged as potentially visibility and thus, being rendered and is not related to the emncipation grill. The second layer of emancipation grill popping in and out of existance is already fixed.

When I was testing this I had culling off using the old cvar at the time which is why I assumed it was due to the emancipation grill since my framerate dropped only when the duplicate was rendered and it happened when leaving the map so the only new thing to be rendered would be the elevator. Also the emancipation grill duplicates are still not fixed. #131

**Comment by Nx0Ri** [comment]
extremely bad performance on map sp_a4_laser_catapult
it lags so bad anywhere, doesnt matter how camera is rotated, or if enhanced assets are turned on, it lags so bad in any condition
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/56162afb-d453-43b4-9002-6350e929150d" />

**Comment by xoxor4d** [comment]
Yup hitting a source engine bottleneck with all of the reduced culling. Fixable with proper setup and remix a mod (prevent source engine from drawing the world and props via cvars, then attach everything to a map marker so its rendered via remix without it going through the d3d9 pipeline)
